/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-body)", "Inter", "ui-sans-serif", "system-ui", "-apple-system"],
        body: ["var(--font-body)", "Inter", "ui-sans-serif", "system-ui", "-apple-system"],
        heading: ["var(--font-heading)", "Inter", "ui-sans-serif", "system-ui", "-apple-system"],
        display: ["var(--font-heading)", "Inter", "ui-sans-serif", "system-ui", "-apple-system"],
        mono: ["SF Mono", "JetBrains Mono", "ui-monospace", "monospace"],
      },
      colors: {
        background: {
          50: "oklch(var(--background-50) / <alpha-value>)",
          100: "oklch(var(--background-100) / <alpha-value>)",
          200: "oklch(var(--background-200) / <alpha-value>)",
          300: "oklch(var(--background-300) / <alpha-value>)",
          400: "oklch(var(--background-400) / <alpha-value>)",
          500: "oklch(var(--background-500) / <alpha-value>)",
          600: "oklch(var(--background-600) / <alpha-value>)",
          700: "oklch(var(--background-700) / <alpha-value>)",
          800: "oklch(var(--background-800) / <alpha-value>)",
          900: "oklch(var(--background-900) / <alpha-value>)",
          950: "oklch(var(--background-950) / <alpha-value>)",
        },
        foreground: {
          50: "oklch(var(--foreground-50) / <alpha-value>)",
          100: "oklch(var(--foreground-100) / <alpha-value>)",
          200: "oklch(var(--foreground-200) / <alpha-value>)",
          300: "oklch(var(--foreground-300) / <alpha-value>)",
          400: "oklch(var(--foreground-400) / <alpha-value>)",
          500: "oklch(var(--foreground-500) / <alpha-value>)",
          600: "oklch(var(--foreground-600) / <alpha-value>)",
          700: "oklch(var(--foreground-700) / <alpha-value>)",
          800: "oklch(var(--foreground-800) / <alpha-value>)",
          900: "oklch(var(--foreground-900) / <alpha-value>)",
          950: "oklch(var(--foreground-950) / <alpha-value>)",
        },
        primary: {
          50: "oklch(var(--primary-50) / <alpha-value>)",
          100: "oklch(var(--primary-100) / <alpha-value>)",
          200: "oklch(var(--primary-200) / <alpha-value>)",
          300: "oklch(var(--primary-300) / <alpha-value>)",
          400: "oklch(var(--primary-400) / <alpha-value>)",
          500: "oklch(var(--primary-500) / <alpha-value>)",
          600: "oklch(var(--primary-600) / <alpha-value>)",
          700: "oklch(var(--primary-700) / <alpha-value>)",
          800: "oklch(var(--primary-800) / <alpha-value>)",
          900: "oklch(var(--primary-900) / <alpha-value>)",
          950: "oklch(var(--primary-950) / <alpha-value>)",
        },
        accent: {
          50: "oklch(var(--accent-50) / <alpha-value>)",
          100: "oklch(var(--accent-100) / <alpha-value>)",
          200: "oklch(var(--accent-200) / <alpha-value>)",
          300: "oklch(var(--accent-300) / <alpha-value>)",
          400: "oklch(var(--accent-400) / <alpha-value>)",
          500: "oklch(var(--accent-500) / <alpha-value>)",
          600: "oklch(var(--accent-600) / <alpha-value>)",
          700: "oklch(var(--accent-700) / <alpha-value>)",
          800: "oklch(var(--accent-800) / <alpha-value>)",
          900: "oklch(var(--accent-900) / <alpha-value>)",
          950: "oklch(var(--accent-950) / <alpha-value>)",
        },
        secondary: {
          50: "oklch(var(--secondary-50) / <alpha-value>)",
          100: "oklch(var(--secondary-100) / <alpha-value>)",
          200: "oklch(var(--secondary-200) / <alpha-value>)",
          300: "oklch(var(--secondary-300) / <alpha-value>)",
          400: "oklch(var(--secondary-400) / <alpha-value>)",
          500: "oklch(var(--secondary-500) / <alpha-value>)",
          600: "oklch(var(--secondary-600) / <alpha-value>)",
          700: "oklch(var(--secondary-700) / <alpha-value>)",
          800: "oklch(var(--secondary-800) / <alpha-value>)",
          900: "oklch(var(--secondary-900) / <alpha-value>)",
          950: "oklch(var(--secondary-950) / <alpha-value>)",
        },
        sidebar: {
          DEFAULT: "oklch(var(--sidebar) / <alpha-value>)",
          fg: "oklch(var(--sidebar-fg) / <alpha-value>)",
          border: "oklch(var(--sidebar-border) / <alpha-value>)",
          accent: "oklch(var(--sidebar-accent) / <alpha-value>)",
          "accent-fg": "oklch(var(--sidebar-accent-fg) / <alpha-value>)",
          ring: "oklch(var(--sidebar-ring) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [],
};